// Code generated by ext/go/internal/pxbgen from schema.go. DO NOT EDIT.

package pxb

// Hello field tags.
const (
	fHelloName     uint16 = 1
	fHelloVersion  uint16 = 2
	fHelloCaps     uint16 = 3
	fHelloProtocol uint16 = 4
)

// sizeHello is the exact wire size of msg.
func sizeHello(msg Hello) int {
	n := 0
	n += strSize(msg.Name)
	n += strSize(msg.Version)
	n += u64FieldSize
	n += u64FieldSize
	return n
}

func EncodeHello(msg Hello) []byte {
	n := sizeHello(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutString(fHelloName, msg.Name)
	fw.PutString(fHelloVersion, msg.Version)
	fw.PutU32(fHelloCaps, msg.Caps)
	fw.PutU16(fHelloProtocol, msg.Protocol)
	return fw.Bytes()
}

func DecodeHello(b []byte) (Hello, error) {
	var msg Hello
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fHelloName:
			s, err := takeString(kind, fr)
			msg.Name = s
			return err
		case fHelloVersion:
			s, err := takeString(kind, fr)
			msg.Version = s
			return err
		case fHelloCaps:
			v, err := takeU64(kind, fr)
			msg.Caps = uint32(v) //nolint:gosec // G115: u32 by protocol
			return err
		case fHelloProtocol:
			v, err := takeU64(kind, fr)
			msg.Protocol = uint16(v) //nolint:gosec // G115: u16 by protocol
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// HelloAck field tags.
const (
	fHelloAckProtocol     uint16 = 1
	fHelloAckPhiVersion   uint16 = 2
	fHelloAckCwd          uint16 = 3
	fHelloAckSessionID    uint16 = 4
	fHelloAckExtensionDir uint16 = 5
)

// sizeHelloAck is the exact wire size of msg.
func sizeHelloAck(msg HelloAck) int {
	n := 0
	n += u64FieldSize
	n += strSize(msg.PhiVersion)
	n += strSize(msg.Cwd)
	n += strSize(msg.SessionID)
	n += strSize(msg.ExtensionDir)
	return n
}

func EncodeHelloAck(msg HelloAck) []byte {
	n := sizeHelloAck(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutU16(fHelloAckProtocol, msg.Protocol)
	fw.PutString(fHelloAckPhiVersion, msg.PhiVersion)
	fw.PutString(fHelloAckCwd, msg.Cwd)
	fw.PutString(fHelloAckSessionID, msg.SessionID)
	fw.PutString(fHelloAckExtensionDir, msg.ExtensionDir)
	return fw.Bytes()
}

func DecodeHelloAck(b []byte) (HelloAck, error) {
	var msg HelloAck
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fHelloAckProtocol:
			v, err := takeU64(kind, fr)
			msg.Protocol = uint16(v) //nolint:gosec // G115: u16 by protocol
			return err
		case fHelloAckPhiVersion:
			s, err := takeString(kind, fr)
			msg.PhiVersion = s
			return err
		case fHelloAckCwd:
			s, err := takeString(kind, fr)
			msg.Cwd = s
			return err
		case fHelloAckSessionID:
			s, err := takeString(kind, fr)
			msg.SessionID = s
			return err
		case fHelloAckExtensionDir:
			s, err := takeString(kind, fr)
			msg.ExtensionDir = s
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// RegisterCommand field tags.
const (
	fRegisterCommandName        uint16 = 1
	fRegisterCommandDescription uint16 = 2
	fRegisterCommandNeedsArgs   uint16 = 3
)

// sizeRegisterCommand is the exact wire size of msg.
func sizeRegisterCommand(msg RegisterCommand) int {
	n := 0
	n += strSize(msg.Name)
	n += strSize(msg.Description)
	if msg.NeedsArgs {
		n += u64FieldSize
	}
	return n
}

func EncodeRegisterCommand(msg RegisterCommand) []byte {
	n := sizeRegisterCommand(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutString(fRegisterCommandName, msg.Name)
	fw.PutString(fRegisterCommandDescription, msg.Description)
	if msg.NeedsArgs {
		fw.PutBool(fRegisterCommandNeedsArgs, msg.NeedsArgs)
	}
	return fw.Bytes()
}

func DecodeRegisterCommand(b []byte) (RegisterCommand, error) {
	var msg RegisterCommand
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fRegisterCommandName:
			s, err := takeString(kind, fr)
			msg.Name = s
			return err
		case fRegisterCommandDescription:
			s, err := takeString(kind, fr)
			msg.Description = s
			return err
		case fRegisterCommandNeedsArgs:
			v, err := takeU64(kind, fr)
			msg.NeedsArgs = v != 0
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// RegisterTool field tags.
const (
	fRegisterToolName        uint16 = 1
	fRegisterToolDescription uint16 = 2
	fRegisterToolSchemaJSON  uint16 = 3
	fRegisterToolTimeoutSec  uint16 = 4
	fRegisterToolHasDetail   uint16 = 5
	fRegisterToolReadable    uint16 = 6
)

// sizeRegisterTool is the exact wire size of msg.
func sizeRegisterTool(msg RegisterTool) int {
	n := 0
	n += strSize(msg.Name)
	n += strSize(msg.Description)
	n += blobSize(msg.SchemaJSON)
	if msg.TimeoutSec > 0 {
		n += u64FieldSize
	}
	if msg.HasDetail {
		n += u64FieldSize
	}
	if msg.Readable {
		n += u64FieldSize
	}
	return n
}

func EncodeRegisterTool(msg RegisterTool) []byte {
	n := sizeRegisterTool(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutString(fRegisterToolName, msg.Name)
	fw.PutString(fRegisterToolDescription, msg.Description)
	fw.PutBytes(fRegisterToolSchemaJSON, msg.SchemaJSON)
	if msg.TimeoutSec > 0 {
		fw.PutU32(fRegisterToolTimeoutSec, msg.TimeoutSec)
	}
	if msg.HasDetail {
		fw.PutBool(fRegisterToolHasDetail, msg.HasDetail)
	}
	if msg.Readable {
		fw.PutBool(fRegisterToolReadable, msg.Readable)
	}
	return fw.Bytes()
}

func DecodeRegisterTool(b []byte) (RegisterTool, error) {
	var msg RegisterTool
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fRegisterToolName:
			s, err := takeString(kind, fr)
			msg.Name = s
			return err
		case fRegisterToolDescription:
			s, err := takeString(kind, fr)
			msg.Description = s
			return err
		case fRegisterToolSchemaJSON:
			p, err := takeBytes(kind, fr)
			msg.SchemaJSON = append([]byte(nil), p...)
			return err
		case fRegisterToolTimeoutSec:
			v, err := takeU64(kind, fr)
			msg.TimeoutSec = uint32(v) //nolint:gosec // G115: u32 by protocol
			return err
		case fRegisterToolHasDetail:
			v, err := takeU64(kind, fr)
			msg.HasDetail = v != 0
			return err
		case fRegisterToolReadable:
			v, err := takeU64(kind, fr)
			msg.Readable = v != 0
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// ToolDetailResult field tags.
const (
	fToolDetailResultDetail uint16 = 1
)

// sizeToolDetailResult is the exact wire size of msg.
func sizeToolDetailResult(msg ToolDetailResult) int {
	n := 0
	n += strSize(msg.Detail)
	return n
}

func EncodeToolDetailResult(msg ToolDetailResult) []byte {
	n := sizeToolDetailResult(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutString(fToolDetailResultDetail, msg.Detail)
	return fw.Bytes()
}

func DecodeToolDetailResult(b []byte) (ToolDetailResult, error) {
	var msg ToolDetailResult
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fToolDetailResultDetail:
			s, err := takeString(kind, fr)
			msg.Detail = s
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// Subscribe field tags.
const (
	fSubscribeEvents    uint16 = 1
	fSubscribeIntercept uint16 = 2
)

// sizeSubscribe is the exact wire size of msg.
func sizeSubscribe(msg Subscribe) int {
	n := 0
	n += u16sSize(msg.Events)
	n += u16sSize(msg.Intercept)
	return n
}

func EncodeSubscribe(msg Subscribe) []byte {
	n := sizeSubscribe(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutU16s(fSubscribeEvents, msg.Events)
	fw.PutU16s(fSubscribeIntercept, msg.Intercept)
	return fw.Bytes()
}

func DecodeSubscribe(b []byte) (Subscribe, error) {
	var msg Subscribe
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fSubscribeEvents:
			p, err := takeBytes(kind, fr)
			if err != nil {
				return err
			}
			msg.Events, err = decodeU16s(p)
			return err
		case fSubscribeIntercept:
			p, err := takeBytes(kind, fr)
			if err != nil {
				return err
			}
			msg.Intercept, err = decodeU16s(p)
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// CommandInvoked field tags.
const (
	fCommandInvokedName uint16 = 1
	fCommandInvokedArgs uint16 = 2
)

// sizeCommandInvoked is the exact wire size of msg.
func sizeCommandInvoked(msg CommandInvoked) int {
	n := 0
	n += strSize(msg.Name)
	n += strSize(msg.Args)
	return n
}

func EncodeCommandInvoked(msg CommandInvoked) []byte {
	n := sizeCommandInvoked(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutString(fCommandInvokedName, msg.Name)
	fw.PutString(fCommandInvokedArgs, msg.Args)
	return fw.Bytes()
}

func DecodeCommandInvoked(b []byte) (CommandInvoked, error) {
	var msg CommandInvoked
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fCommandInvokedName:
			s, err := takeString(kind, fr)
			msg.Name = s
			return err
		case fCommandInvokedArgs:
			s, err := takeString(kind, fr)
			msg.Args = s
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// CommandResponse field tags.
const (
	fCommandResponseOK     uint16 = 1
	fCommandResponseError  uint16 = 2
	fCommandResponseNotify uint16 = 3
	fCommandResponseSubmit uint16 = 4
)

// sizeCommandResponse is the exact wire size of msg.
func sizeCommandResponse(msg CommandResponse) int {
	n := 0
	n += u64FieldSize
	n += strSize(msg.Error)
	n += strSize(msg.Notify)
	n += strSize(msg.Submit)
	return n
}

func EncodeCommandResponse(msg CommandResponse) []byte {
	n := sizeCommandResponse(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutBool(fCommandResponseOK, msg.OK)
	fw.PutString(fCommandResponseError, msg.Error)
	fw.PutString(fCommandResponseNotify, msg.Notify)
	fw.PutString(fCommandResponseSubmit, msg.Submit)
	return fw.Bytes()
}

func DecodeCommandResponse(b []byte) (CommandResponse, error) {
	var msg CommandResponse
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fCommandResponseOK:
			v, err := takeU64(kind, fr)
			msg.OK = v != 0
			return err
		case fCommandResponseError:
			s, err := takeString(kind, fr)
			msg.Error = s
			return err
		case fCommandResponseNotify:
			s, err := takeString(kind, fr)
			msg.Notify = s
			return err
		case fCommandResponseSubmit:
			s, err := takeString(kind, fr)
			msg.Submit = s
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// ToolInvoke field tags.
const (
	fToolInvokeName uint16 = 1
	fToolInvokeArgs uint16 = 2
)

// sizeToolInvoke is the exact wire size of msg.
func sizeToolInvoke(msg ToolInvoke) int {
	n := 0
	n += strSize(msg.Name)
	n += blobSize(msg.Args)
	return n
}

func EncodeToolInvoke(msg ToolInvoke) []byte {
	n := sizeToolInvoke(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutString(fToolInvokeName, msg.Name)
	fw.PutBytes(fToolInvokeArgs, msg.Args)
	return fw.Bytes()
}

func DecodeToolInvoke(b []byte) (ToolInvoke, error) {
	var msg ToolInvoke
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fToolInvokeName:
			s, err := takeString(kind, fr)
			msg.Name = s
			return err
		case fToolInvokeArgs:
			p, err := takeBytes(kind, fr)
			msg.Args = append([]byte(nil), p...)
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// ToolResultMsg field tags.
const (
	fToolResultContent  uint16 = 1
	fToolResultDetail   uint16 = 2
	fToolResultOutput   uint16 = 3
	fToolResultIsError  uint16 = 4
	fToolResultError    uint16 = 5
	fToolResultExpanded uint16 = 6
)

// sizeToolResult is the exact wire size of msg.
func sizeToolResult(msg ToolResultMsg) int {
	n := 0
	n += strSize(msg.Content)
	n += strSize(msg.Detail)
	n += strSize(msg.Output)
	n += u64FieldSize
	n += strSize(msg.Error)
	if msg.Expanded {
		n += u64FieldSize
	}
	return n
}

func EncodeToolResult(msg ToolResultMsg) []byte {
	n := sizeToolResult(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutString(fToolResultContent, msg.Content)
	fw.PutString(fToolResultDetail, msg.Detail)
	fw.PutString(fToolResultOutput, msg.Output)
	fw.PutBool(fToolResultIsError, msg.IsError)
	fw.PutString(fToolResultError, msg.Error)
	if msg.Expanded {
		fw.PutBool(fToolResultExpanded, msg.Expanded)
	}
	return fw.Bytes()
}

func DecodeToolResult(b []byte) (ToolResultMsg, error) {
	var msg ToolResultMsg
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fToolResultContent:
			s, err := takeString(kind, fr)
			msg.Content = s
			return err
		case fToolResultDetail:
			s, err := takeString(kind, fr)
			msg.Detail = s
			return err
		case fToolResultOutput:
			s, err := takeString(kind, fr)
			msg.Output = s
			return err
		case fToolResultIsError:
			v, err := takeU64(kind, fr)
			msg.IsError = v != 0
			return err
		case fToolResultError:
			s, err := takeString(kind, fr)
			msg.Error = s
			return err
		case fToolResultExpanded:
			v, err := takeU64(kind, fr)
			msg.Expanded = v != 0
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// InterceptReq field tags.
const (
	fInterceptReqEvent      uint16 = 1
	fInterceptReqToolName   uint16 = 2
	fInterceptReqToolCallID uint16 = 3
	fInterceptReqInput      uint16 = 4
	fInterceptReqContent    uint16 = 5
	fInterceptReqIsError    uint16 = 6
	fInterceptReqErrText    uint16 = 7
	fInterceptReqPrompt     uint16 = 8
	fInterceptReqReason     uint16 = 9
	fInterceptReqTargetID   uint16 = 10
	fInterceptReqTurnIndex  uint16 = 11
)

// sizeInterceptReq is the exact wire size of msg.
func sizeInterceptReq(msg InterceptReq) int {
	n := 0
	n += u64FieldSize
	n += strSize(msg.ToolName)
	n += strSize(msg.ToolCallID)
	n += blobSize(msg.Input)
	n += strSize(msg.Content)
	n += u64FieldSize
	n += strSize(msg.ErrText)
	n += strSize(msg.Prompt)
	n += strSize(msg.Reason)
	n += strSize(msg.TargetID)
	n += u64FieldSize
	return n
}

func EncodeInterceptReq(msg InterceptReq) []byte {
	n := sizeInterceptReq(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutU16(fInterceptReqEvent, msg.Event)
	fw.PutString(fInterceptReqToolName, msg.ToolName)
	fw.PutString(fInterceptReqToolCallID, msg.ToolCallID)
	fw.PutBytes(fInterceptReqInput, msg.Input)
	fw.PutString(fInterceptReqContent, msg.Content)
	fw.PutBool(fInterceptReqIsError, msg.IsError)
	fw.PutString(fInterceptReqErrText, msg.ErrText)
	fw.PutString(fInterceptReqPrompt, msg.Prompt)
	fw.PutString(fInterceptReqReason, msg.Reason)
	fw.PutString(fInterceptReqTargetID, msg.TargetID)
	fw.PutU32(fInterceptReqTurnIndex, msg.TurnIndex)
	return fw.Bytes()
}

func DecodeInterceptReq(b []byte) (InterceptReq, error) {
	var msg InterceptReq
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fInterceptReqEvent:
			v, err := takeU64(kind, fr)
			msg.Event = uint16(v) //nolint:gosec // G115: u16 by protocol
			return err
		case fInterceptReqToolName:
			s, err := takeString(kind, fr)
			msg.ToolName = s
			return err
		case fInterceptReqToolCallID:
			s, err := takeString(kind, fr)
			msg.ToolCallID = s
			return err
		case fInterceptReqInput:
			p, err := takeBytes(kind, fr)
			msg.Input = append([]byte(nil), p...)
			return err
		case fInterceptReqContent:
			s, err := takeString(kind, fr)
			msg.Content = s
			return err
		case fInterceptReqIsError:
			v, err := takeU64(kind, fr)
			msg.IsError = v != 0
			return err
		case fInterceptReqErrText:
			s, err := takeString(kind, fr)
			msg.ErrText = s
			return err
		case fInterceptReqPrompt:
			s, err := takeString(kind, fr)
			msg.Prompt = s
			return err
		case fInterceptReqReason:
			s, err := takeString(kind, fr)
			msg.Reason = s
			return err
		case fInterceptReqTargetID:
			s, err := takeString(kind, fr)
			msg.TargetID = s
			return err
		case fInterceptReqTurnIndex:
			v, err := takeU64(kind, fr)
			msg.TurnIndex = uint32(v) //nolint:gosec // G115: u32 by protocol
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// InterceptResp field tags.
const (
	fInterceptRespBlock              uint16 = 1
	fInterceptRespStop               uint16 = 2
	fInterceptRespCancel             uint16 = 3
	fInterceptRespReason             uint16 = 4
	fInterceptRespInput              uint16 = 5
	fInterceptRespContent            uint16 = 6
	fInterceptRespContext            uint16 = 7
	fInterceptRespSystemPromptAppend uint16 = 8
	fInterceptRespToast              uint16 = 9
	fInterceptRespHandled            uint16 = 10
	fInterceptRespPrompt             uint16 = 11
	fInterceptRespContinue           uint16 = 12
)

// sizeInterceptResp is the exact wire size of msg.
func sizeInterceptResp(msg InterceptResp) int {
	n := 0
	n += u64FieldSize
	n += u64FieldSize
	n += u64FieldSize
	n += strSize(msg.Reason)
	n += blobSize(msg.Input)
	n += strSize(msg.Content)
	n += strSize(msg.Context)
	n += strSize(msg.SystemPromptAppend)
	n += strSize(msg.Toast)
	n += u64FieldSize
	n += strSize(msg.Prompt)
	n += u64FieldSize
	return n
}

func EncodeInterceptResp(msg InterceptResp) []byte {
	n := sizeInterceptResp(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutBool(fInterceptRespBlock, msg.Block)
	fw.PutBool(fInterceptRespStop, msg.Stop)
	fw.PutBool(fInterceptRespCancel, msg.Cancel)
	fw.PutString(fInterceptRespReason, msg.Reason)
	fw.PutBytes(fInterceptRespInput, msg.Input)
	fw.PutString(fInterceptRespContent, msg.Content)
	fw.PutString(fInterceptRespContext, msg.Context)
	fw.PutString(fInterceptRespSystemPromptAppend, msg.SystemPromptAppend)
	fw.PutString(fInterceptRespToast, msg.Toast)
	fw.PutBool(fInterceptRespHandled, msg.Handled)
	fw.PutString(fInterceptRespPrompt, msg.Prompt)
	fw.PutBool(fInterceptRespContinue, msg.Continue)
	return fw.Bytes()
}

func DecodeInterceptResp(b []byte) (InterceptResp, error) {
	var msg InterceptResp
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fInterceptRespBlock:
			v, err := takeU64(kind, fr)
			msg.Block = v != 0
			return err
		case fInterceptRespStop:
			v, err := takeU64(kind, fr)
			msg.Stop = v != 0
			return err
		case fInterceptRespCancel:
			v, err := takeU64(kind, fr)
			msg.Cancel = v != 0
			return err
		case fInterceptRespReason:
			s, err := takeString(kind, fr)
			msg.Reason = s
			return err
		case fInterceptRespInput:
			p, err := takeBytes(kind, fr)
			msg.Input = append([]byte(nil), p...)
			return err
		case fInterceptRespContent:
			s, err := takeString(kind, fr)
			msg.Content = s
			return err
		case fInterceptRespContext:
			s, err := takeString(kind, fr)
			msg.Context = s
			return err
		case fInterceptRespSystemPromptAppend:
			s, err := takeString(kind, fr)
			msg.SystemPromptAppend = s
			return err
		case fInterceptRespToast:
			s, err := takeString(kind, fr)
			msg.Toast = s
			return err
		case fInterceptRespHandled:
			v, err := takeU64(kind, fr)
			msg.Handled = v != 0
			return err
		case fInterceptRespPrompt:
			s, err := takeString(kind, fr)
			msg.Prompt = s
			return err
		case fInterceptRespContinue:
			v, err := takeU64(kind, fr)
			msg.Continue = v != 0
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// EventNotify field tags.
const (
	fEventNotifyEvent             uint16 = 1
	fEventNotifyToolName          uint16 = 2
	fEventNotifyToolCallID        uint16 = 3
	fEventNotifyInput             uint16 = 4
	fEventNotifyIsError           uint16 = 5
	fEventNotifyPrompt            uint16 = 6
	fEventNotifyReason            uint16 = 7
	fEventNotifyTurnIndex         uint16 = 8
	fEventNotifySessionID         uint16 = 9
	fEventNotifyPreviousSessionID uint16 = 10
	fEventNotifyTargetSessionID   uint16 = 11
)

// sizeEventNotify is the exact wire size of msg.
func sizeEventNotify(msg EventNotify) int {
	n := 0
	n += u64FieldSize
	n += strSize(msg.ToolName)
	n += strSize(msg.ToolCallID)
	n += blobSize(msg.Input)
	n += u64FieldSize
	n += strSize(msg.Prompt)
	n += strSize(msg.Reason)
	n += u64FieldSize
	n += strSize(msg.SessionID)
	n += strSize(msg.PreviousSessionID)
	n += strSize(msg.TargetSessionID)
	return n
}

func EncodeEventNotify(msg EventNotify) []byte {
	n := sizeEventNotify(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutU16(fEventNotifyEvent, msg.Event)
	fw.PutString(fEventNotifyToolName, msg.ToolName)
	fw.PutString(fEventNotifyToolCallID, msg.ToolCallID)
	fw.PutBytes(fEventNotifyInput, msg.Input)
	fw.PutBool(fEventNotifyIsError, msg.IsError)
	fw.PutString(fEventNotifyPrompt, msg.Prompt)
	fw.PutString(fEventNotifyReason, msg.Reason)
	fw.PutU32(fEventNotifyTurnIndex, msg.TurnIndex)
	fw.PutString(fEventNotifySessionID, msg.SessionID)
	fw.PutString(fEventNotifyPreviousSessionID, msg.PreviousSessionID)
	fw.PutString(fEventNotifyTargetSessionID, msg.TargetSessionID)
	return fw.Bytes()
}

func DecodeEventNotify(b []byte) (EventNotify, error) {
	var msg EventNotify
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fEventNotifyEvent:
			v, err := takeU64(kind, fr)
			msg.Event = uint16(v) //nolint:gosec // G115: u16 by protocol
			return err
		case fEventNotifyToolName:
			s, err := takeString(kind, fr)
			msg.ToolName = s
			return err
		case fEventNotifyToolCallID:
			s, err := takeString(kind, fr)
			msg.ToolCallID = s
			return err
		case fEventNotifyInput:
			p, err := takeBytes(kind, fr)
			msg.Input = append([]byte(nil), p...)
			return err
		case fEventNotifyIsError:
			v, err := takeU64(kind, fr)
			msg.IsError = v != 0
			return err
		case fEventNotifyPrompt:
			s, err := takeString(kind, fr)
			msg.Prompt = s
			return err
		case fEventNotifyReason:
			s, err := takeString(kind, fr)
			msg.Reason = s
			return err
		case fEventNotifyTurnIndex:
			v, err := takeU64(kind, fr)
			msg.TurnIndex = uint32(v) //nolint:gosec // G115: u32 by protocol
			return err
		case fEventNotifySessionID:
			s, err := takeString(kind, fr)
			msg.SessionID = s
			return err
		case fEventNotifyPreviousSessionID:
			s, err := takeString(kind, fr)
			msg.PreviousSessionID = s
			return err
		case fEventNotifyTargetSessionID:
			s, err := takeString(kind, fr)
			msg.TargetSessionID = s
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// NotifyMsg field tags.
const (
	fNotifyLevel     uint16 = 1
	fNotifyMessage   uint16 = 2
	fNotifyStatus    uint16 = 3
	fNotifyStatusSet uint16 = 4
)

// sizeNotify is the exact wire size of msg.
func sizeNotify(msg NotifyMsg) int {
	n := 0
	n += strSize(msg.Level)
	n += strSize(msg.Message)
	n += strSize(msg.Status)
	n += u64FieldSize
	return n
}

func EncodeNotify(msg NotifyMsg) []byte {
	n := sizeNotify(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutString(fNotifyLevel, msg.Level)
	fw.PutString(fNotifyMessage, msg.Message)
	fw.PutString(fNotifyStatus, msg.Status)
	fw.PutBool(fNotifyStatusSet, msg.StatusSet)
	return fw.Bytes()
}

func DecodeNotify(b []byte) (NotifyMsg, error) {
	var msg NotifyMsg
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fNotifyLevel:
			s, err := takeString(kind, fr)
			msg.Level = s
			return err
		case fNotifyMessage:
			s, err := takeString(kind, fr)
			msg.Message = s
			return err
		case fNotifyStatus:
			s, err := takeString(kind, fr)
			msg.Status = s
			return err
		case fNotifyStatusSet:
			v, err := takeU64(kind, fr)
			msg.StatusSet = v != 0
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// HostRequest field tags.
const (
	fHostRequestMethod uint16 = 1
	fHostRequestArg    uint16 = 2
)

// sizeHostRequest is the exact wire size of msg.
func sizeHostRequest(msg HostRequest) int {
	n := 0
	n += strSize(msg.Method)
	n += strSize(msg.Arg)
	return n
}

func EncodeHostRequest(msg HostRequest) []byte {
	n := sizeHostRequest(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutString(fHostRequestMethod, msg.Method)
	fw.PutString(fHostRequestArg, msg.Arg)
	return fw.Bytes()
}

func DecodeHostRequest(b []byte) (HostRequest, error) {
	var msg HostRequest
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fHostRequestMethod:
			s, err := takeString(kind, fr)
			msg.Method = s
			return err
		case fHostRequestArg:
			s, err := takeString(kind, fr)
			msg.Arg = s
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// HostResult field tags.
const (
	fHostResultOK    uint16 = 1
	fHostResultError uint16 = 2
	fHostResultBody  uint16 = 3
)

// sizeHostResult is the exact wire size of msg.
func sizeHostResult(msg HostResult) int {
	n := 0
	n += u64FieldSize
	n += strSize(msg.Error)
	n += strSize(msg.Body)
	return n
}

func EncodeHostResult(msg HostResult) []byte {
	n := sizeHostResult(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutBool(fHostResultOK, msg.OK)
	fw.PutString(fHostResultError, msg.Error)
	fw.PutString(fHostResultBody, msg.Body)
	return fw.Bytes()
}

func DecodeHostResult(b []byte) (HostResult, error) {
	var msg HostResult
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fHostResultOK:
			v, err := takeU64(kind, fr)
			msg.OK = v != 0
			return err
		case fHostResultError:
			s, err := takeString(kind, fr)
			msg.Error = s
			return err
		case fHostResultBody:
			s, err := takeString(kind, fr)
			msg.Body = s
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}

// SessionMeta field tags.
const (
	fSessionMetaSessionID uint16 = 1
	fSessionMetaCwd       uint16 = 2
)

// sizeSessionMeta is the exact wire size of msg.
func sizeSessionMeta(msg SessionMeta) int {
	n := 0
	n += strSize(msg.SessionID)
	n += strSize(msg.Cwd)
	return n
}

func EncodeSessionMeta(msg SessionMeta) []byte {
	n := sizeSessionMeta(msg)
	if n == 0 {
		return nil
	}
	fw := sizedWriter(n)
	fw.PutString(fSessionMetaSessionID, msg.SessionID)
	fw.PutString(fSessionMetaCwd, msg.Cwd)
	return fw.Bytes()
}

func DecodeSessionMeta(b []byte) (SessionMeta, error) {
	var msg SessionMeta
	err := Walk(b, func(tag uint16, kind uint8, fr *FieldReader) error {
		switch tag {
		case fSessionMetaSessionID:
			s, err := takeString(kind, fr)
			msg.SessionID = s
			return err
		case fSessionMetaCwd:
			s, err := takeString(kind, fr)
			msg.Cwd = s
			return err
		default:
			return fr.Skip(kind)
		}
	})
	return msg, err
}
